---
downloads: /tmp

configure_ui: true

install_base: true
base_packages:
  - bat
  - gh
  - git
  - iperf
  - jq
  - kodi
  - nmap
  - neofetch
  - openconnect
  - openssl
  - packer
  - shellcheck
  - terraform
  - tree
  - unzip
  - vagrant
  - vault
  - zsh

install_extra: true
extra_strict_packages:
  - brave
  - discord
  - postman
  - spotify
  - vlc
  - zoom-client

extra_classic_packages:
  - codium
  - slack

install_vbox: true
vbox_packages:
  - virtualbox

install_docker: true
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose

vscode_extensions:
  - vscode-icons-team.vscode-icons
  - zhuangtongfa.material-theme
  - redhat.ansible
  - redhat.vscode-yaml
  - redhat.vscode-xml
  - shardulm94.trailing-spaces
  - eamodio.gitlens
  - ms-python.python
  - ms-python.vscode-pylance
  - yzhang.markdown-all-in-one
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-containers

install_python_dev: true
build_packages:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev

install_java: true
java_packages:
  - default-jre

install_ruby_dev: true
ruby_packages:
  - build-essential
  - ruby-full
  - zlib1g-dev
ruby_gems:
  - bundler
  - jekyll