---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include custom configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Ensure apt cache is updated.
      apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  tasks:
    - import_tasks: tasks/ui.yml
      tags: ['ui-theme']
      when: configure_ui

    - import_tasks: tasks/base-packages.yml
      tags: ['base-packages']
      when: install_base

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
      when: install_extra

    - import_tasks: tasks/launcher.yml
      tags: ['ui-launcher']
      when: configure_ui

    - import_tasks: tasks/terminal.yml
      tags: ['ui-terminal']
      when: configure_ui

    - import_tasks: tasks/python-dev.yml
      tags: ['python-dev']
      when: install_python_dev

    - import_tasks: tasks/ruby-dev.yml
      tags: ['ruby-dev']
      when: install_ruby_dev
