---
- name: Ensure apt key for gh cli is present.
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 23F3D4EA75716059
  become: true

- name: Ensure apt key for hashicorp is present.
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: Ensure repository for hashicorp is present.
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ ansible_lsb.codename }}  main
    state: present
  become: true

# - name: Ensure repository for github cli is present.
#   ansible.builtin.apt_repository:
#     repo: deb https://cli.github.com/packages {{ ansible_lsb.codename }} main
#     state: present
#   become: true

- name: Ensure repository for git is present.
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present
  become: true

- name: Ensure repository for kodi is present.
  ansible.builtin.apt_repository:
    repo: ppa:team-xbmc/ppa
    state: present
  become: true

- name: Ensure base apt packages are present.
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
  become: true

- name: Check if batcat is present.
  ansible.builtin.stat:
    path: /usr/bin/batcat
  register: batcat

- name: Create a symlink for bat.
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
  become: true
  when: batcat.stat.exists
