---
- name: Ensure apt key for docker is present.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  when: install_docker

- name: Ensure repository for docker is present.
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
  become: true
  when: install_docker

- name: Ensure docker and docker tools are present.
  apt:
    name: "{{ docker_packages }}"
    state: present
  become: true
  when: install_docker

- name: Ensure the current user is part of docker group.
  user:
    name: "{{ansible_user|default(lookup('env', 'USER')) }}"
    groups: docker
    append: yes
  become: true

- name: Ensure extra snap strict packages are present.
  snap:
    name: "{{ extra_strict_packages }}"
    state: present
  become: true

- name: Ensure extra snap classic packages are present.
  snap:
    name: "{{ extra_classic_packages }}"
    classic: true
    state: present
  become: true

- name: Ensure vbox and vbox tools are present.
  apt:
    name: "{{ vbox_packages }}"
    state: present
  become: true
  when: install_vbox

- name: Ensure java runtime is present.
  apt:
    name: "{{ java_packages }}"
    state: present
  become: true
  when: install_java

- name: Ensure megasync is present.
  apt:
    name: megasync
  become: true

- name: Ensure Raspberry Pi Imager is present.
  apt:
    deb: "https://downloads.raspberrypi.org/imager/imager_latest_amd64.deb"
  become: true

- name: Install Codium Extensions.
  command: codium --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  changed_when: false
