---
- name: Ensure Meslo Nerd Font directory is present.
  file:
    path: "/usr/local/share/fonts/MesloLGS NF"
    state: directory
    mode: 0755
  become: true

- name: Ensure Meslo Nerd font files are present.
  get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20{{ item | urlencode() }}.ttf"
    dest: "/usr/local/share/fonts/MesloLGS NF/MesloLGS NF {{ item }}.ttf"
  with_items:
    - "Regular"
    - "Bold"
    - "Italic"
    - "Bold Italic"
  become: true
